### ISSUE TITLE
Attach Data disk to VMSS using Java SDK?

### ISSUE THREAD

**Issue by prafulbusa** [Azure-Samples/compute-java-manage-virtual-machine-scale-sets#6]
Hello Guys, 

Can you help me using Java SDK to attach data disk to VMSS in Azure?

**Comment by anuchandy** [comment]
@prafulbusa here is the code to create VMSS with data disks attached https://github.com/Azure/azure-libraries-for-java/blob/75a9b05c4eb9b553195f3876583756063e18ba5a/azure-mgmt-compute/src/test/java/com/microsoft/azure/management/compute/VirtualMachineScaleSetManagedDiskOperationsTests.java#L34

**Comment by prafulbusa** [comment]
Thank you @anuchandy 

I had a case there cx needed help and I believe he will be happy to see your reply.

**Comment by kramimus** [comment]
This was very helpful, thanks. 

We are also interested attaching pre-populated disks to an existing scale set (in addition to this empty dataDisk case), is there Java SDK functionality to this? I believe this functionality is outlined here: https://github.com/Azure/vm-scale-sets/tree/master/preview/disk
